// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/seizadi/test/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	resource "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"
	_ "github.com/infobloxopen/protoc-gen-atlas-query-validate/options"
	_ "github.com/infobloxopen/protoc-gen-atlas-validate/options"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "github.com/lyft/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ---------------------------------
// TEST Application Version
// ---------------------------------
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// ---------------------------------------------------------
// Application
// ---------------------------------------------------------
type Application struct {
	// The Application identifier.
	Id *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the Application
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the Application
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{1}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateApplicationRequest struct {
	Payload              *Application `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateApplicationRequest) Reset()         { *m = CreateApplicationRequest{} }
func (m *CreateApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateApplicationRequest) ProtoMessage()    {}
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{2}
}

func (m *CreateApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApplicationRequest.Unmarshal(m, b)
}
func (m *CreateApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApplicationRequest.Marshal(b, m, deterministic)
}
func (m *CreateApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApplicationRequest.Merge(m, src)
}
func (m *CreateApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateApplicationRequest.Size(m)
}
func (m *CreateApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApplicationRequest proto.InternalMessageInfo

func (m *CreateApplicationRequest) GetPayload() *Application {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateApplicationResponse struct {
	Result               *Application `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateApplicationResponse) Reset()         { *m = CreateApplicationResponse{} }
func (m *CreateApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateApplicationResponse) ProtoMessage()    {}
func (*CreateApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{3}
}

func (m *CreateApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApplicationResponse.Unmarshal(m, b)
}
func (m *CreateApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApplicationResponse.Marshal(b, m, deterministic)
}
func (m *CreateApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApplicationResponse.Merge(m, src)
}
func (m *CreateApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateApplicationResponse.Size(m)
}
func (m *CreateApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApplicationResponse proto.InternalMessageInfo

func (m *CreateApplicationResponse) GetResult() *Application {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadApplicationRequest struct {
	Id                   *resource.Identifier  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadApplicationRequest) Reset()         { *m = ReadApplicationRequest{} }
func (m *ReadApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*ReadApplicationRequest) ProtoMessage()    {}
func (*ReadApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{4}
}

func (m *ReadApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadApplicationRequest.Unmarshal(m, b)
}
func (m *ReadApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadApplicationRequest.Marshal(b, m, deterministic)
}
func (m *ReadApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadApplicationRequest.Merge(m, src)
}
func (m *ReadApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_ReadApplicationRequest.Size(m)
}
func (m *ReadApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadApplicationRequest proto.InternalMessageInfo

func (m *ReadApplicationRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ReadApplicationRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReadApplicationResponse struct {
	Result               *Application `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReadApplicationResponse) Reset()         { *m = ReadApplicationResponse{} }
func (m *ReadApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*ReadApplicationResponse) ProtoMessage()    {}
func (*ReadApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{5}
}

func (m *ReadApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadApplicationResponse.Unmarshal(m, b)
}
func (m *ReadApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadApplicationResponse.Marshal(b, m, deterministic)
}
func (m *ReadApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadApplicationResponse.Merge(m, src)
}
func (m *ReadApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_ReadApplicationResponse.Size(m)
}
func (m *ReadApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadApplicationResponse proto.InternalMessageInfo

func (m *ReadApplicationResponse) GetResult() *Application {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateApplicationRequest struct {
	Payload              *Application          `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateApplicationRequest) Reset()         { *m = UpdateApplicationRequest{} }
func (m *UpdateApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateApplicationRequest) ProtoMessage()    {}
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{6}
}

func (m *UpdateApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateApplicationRequest.Unmarshal(m, b)
}
func (m *UpdateApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateApplicationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateApplicationRequest.Merge(m, src)
}
func (m *UpdateApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateApplicationRequest.Size(m)
}
func (m *UpdateApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateApplicationRequest proto.InternalMessageInfo

func (m *UpdateApplicationRequest) GetPayload() *Application {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateApplicationRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UpdateApplicationResponse struct {
	Result               *Application `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateApplicationResponse) Reset()         { *m = UpdateApplicationResponse{} }
func (m *UpdateApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateApplicationResponse) ProtoMessage()    {}
func (*UpdateApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{7}
}

func (m *UpdateApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateApplicationResponse.Unmarshal(m, b)
}
func (m *UpdateApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateApplicationResponse.Marshal(b, m, deterministic)
}
func (m *UpdateApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateApplicationResponse.Merge(m, src)
}
func (m *UpdateApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateApplicationResponse.Size(m)
}
func (m *UpdateApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateApplicationResponse proto.InternalMessageInfo

func (m *UpdateApplicationResponse) GetResult() *Application {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteApplicationRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteApplicationRequest) Reset()         { *m = DeleteApplicationRequest{} }
func (m *DeleteApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteApplicationRequest) ProtoMessage()    {}
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{8}
}

func (m *DeleteApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteApplicationRequest.Unmarshal(m, b)
}
func (m *DeleteApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteApplicationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteApplicationRequest.Merge(m, src)
}
func (m *DeleteApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteApplicationRequest.Size(m)
}
func (m *DeleteApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteApplicationRequest proto.InternalMessageInfo

func (m *DeleteApplicationRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteApplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteApplicationResponse) Reset()         { *m = DeleteApplicationResponse{} }
func (m *DeleteApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteApplicationResponse) ProtoMessage()    {}
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{9}
}

func (m *DeleteApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteApplicationResponse.Unmarshal(m, b)
}
func (m *DeleteApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteApplicationResponse.Marshal(b, m, deterministic)
}
func (m *DeleteApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteApplicationResponse.Merge(m, src)
}
func (m *DeleteApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteApplicationResponse.Size(m)
}
func (m *DeleteApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteApplicationResponse proto.InternalMessageInfo

type ListApplicationRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListApplicationRequest) Reset()         { *m = ListApplicationRequest{} }
func (m *ListApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*ListApplicationRequest) ProtoMessage()    {}
func (*ListApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{10}
}

func (m *ListApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationRequest.Unmarshal(m, b)
}
func (m *ListApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationRequest.Marshal(b, m, deterministic)
}
func (m *ListApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationRequest.Merge(m, src)
}
func (m *ListApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_ListApplicationRequest.Size(m)
}
func (m *ListApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationRequest proto.InternalMessageInfo

func (m *ListApplicationRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListApplicationRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListApplicationRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListApplicationRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListApplicationsResponse struct {
	Results              []*Application  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page                 *query.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListApplicationsResponse) Reset()         { *m = ListApplicationsResponse{} }
func (m *ListApplicationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListApplicationsResponse) ProtoMessage()    {}
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{11}
}

func (m *ListApplicationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplicationsResponse.Unmarshal(m, b)
}
func (m *ListApplicationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplicationsResponse.Marshal(b, m, deterministic)
}
func (m *ListApplicationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplicationsResponse.Merge(m, src)
}
func (m *ListApplicationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListApplicationsResponse.Size(m)
}
func (m *ListApplicationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplicationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplicationsResponse proto.InternalMessageInfo

func (m *ListApplicationsResponse) GetResults() []*Application {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListApplicationsResponse) GetPage() *query.PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

// -------------------------------------------------
// Event
// -------------------------------------------------
type Event struct {
	// The Event identifier.
	Id *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the Event
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the Event
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The timestamp of the Event
	EventTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	// Reference to Application
	ApplicationId        *resource.Identifier `protobuf:"bytes,5,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{12}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetEventTime() *timestamp.Timestamp {
	if m != nil {
		return m.EventTime
	}
	return nil
}

func (m *Event) GetApplicationId() *resource.Identifier {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

type CreateEventRequest struct {
	Payload              *Event   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventRequest) Reset()         { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()    {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{13}
}

func (m *CreateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequest.Unmarshal(m, b)
}
func (m *CreateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequest.Marshal(b, m, deterministic)
}
func (m *CreateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequest.Merge(m, src)
}
func (m *CreateEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequest.Size(m)
}
func (m *CreateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequest proto.InternalMessageInfo

func (m *CreateEventRequest) GetPayload() *Event {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateEventResponse struct {
	Result               *Event   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventResponse) Reset()         { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()    {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{14}
}

func (m *CreateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventResponse.Unmarshal(m, b)
}
func (m *CreateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventResponse.Marshal(b, m, deterministic)
}
func (m *CreateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventResponse.Merge(m, src)
}
func (m *CreateEventResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEventResponse.Size(m)
}
func (m *CreateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventResponse proto.InternalMessageInfo

func (m *CreateEventResponse) GetResult() *Event {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadEventRequest struct {
	Id                   *resource.Identifier  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadEventRequest) Reset()         { *m = ReadEventRequest{} }
func (m *ReadEventRequest) String() string { return proto.CompactTextString(m) }
func (*ReadEventRequest) ProtoMessage()    {}
func (*ReadEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{15}
}

func (m *ReadEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadEventRequest.Unmarshal(m, b)
}
func (m *ReadEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadEventRequest.Marshal(b, m, deterministic)
}
func (m *ReadEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadEventRequest.Merge(m, src)
}
func (m *ReadEventRequest) XXX_Size() int {
	return xxx_messageInfo_ReadEventRequest.Size(m)
}
func (m *ReadEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadEventRequest proto.InternalMessageInfo

func (m *ReadEventRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ReadEventRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReadEventResponse struct {
	Result               *Event   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadEventResponse) Reset()         { *m = ReadEventResponse{} }
func (m *ReadEventResponse) String() string { return proto.CompactTextString(m) }
func (*ReadEventResponse) ProtoMessage()    {}
func (*ReadEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{16}
}

func (m *ReadEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadEventResponse.Unmarshal(m, b)
}
func (m *ReadEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadEventResponse.Marshal(b, m, deterministic)
}
func (m *ReadEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadEventResponse.Merge(m, src)
}
func (m *ReadEventResponse) XXX_Size() int {
	return xxx_messageInfo_ReadEventResponse.Size(m)
}
func (m *ReadEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadEventResponse proto.InternalMessageInfo

func (m *ReadEventResponse) GetResult() *Event {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateEventRequest struct {
	Payload              *Event                `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateEventRequest) Reset()         { *m = UpdateEventRequest{} }
func (m *UpdateEventRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEventRequest) ProtoMessage()    {}
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{17}
}

func (m *UpdateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEventRequest.Unmarshal(m, b)
}
func (m *UpdateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEventRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEventRequest.Merge(m, src)
}
func (m *UpdateEventRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEventRequest.Size(m)
}
func (m *UpdateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEventRequest proto.InternalMessageInfo

func (m *UpdateEventRequest) GetPayload() *Event {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateEventRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UpdateEventResponse struct {
	Result               *Event   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEventResponse) Reset()         { *m = UpdateEventResponse{} }
func (m *UpdateEventResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateEventResponse) ProtoMessage()    {}
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{18}
}

func (m *UpdateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEventResponse.Unmarshal(m, b)
}
func (m *UpdateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEventResponse.Marshal(b, m, deterministic)
}
func (m *UpdateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEventResponse.Merge(m, src)
}
func (m *UpdateEventResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateEventResponse.Size(m)
}
func (m *UpdateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEventResponse proto.InternalMessageInfo

func (m *UpdateEventResponse) GetResult() *Event {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteEventRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteEventRequest) Reset()         { *m = DeleteEventRequest{} }
func (m *DeleteEventRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEventRequest) ProtoMessage()    {}
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{19}
}

func (m *DeleteEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventRequest.Unmarshal(m, b)
}
func (m *DeleteEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventRequest.Merge(m, src)
}
func (m *DeleteEventRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEventRequest.Size(m)
}
func (m *DeleteEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventRequest proto.InternalMessageInfo

func (m *DeleteEventRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventResponse) Reset()         { *m = DeleteEventResponse{} }
func (m *DeleteEventResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteEventResponse) ProtoMessage()    {}
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{20}
}

func (m *DeleteEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventResponse.Unmarshal(m, b)
}
func (m *DeleteEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventResponse.Marshal(b, m, deterministic)
}
func (m *DeleteEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventResponse.Merge(m, src)
}
func (m *DeleteEventResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteEventResponse.Size(m)
}
func (m *DeleteEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventResponse proto.InternalMessageInfo

type ListEventRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListEventRequest) Reset()         { *m = ListEventRequest{} }
func (m *ListEventRequest) String() string { return proto.CompactTextString(m) }
func (*ListEventRequest) ProtoMessage()    {}
func (*ListEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{21}
}

func (m *ListEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventRequest.Unmarshal(m, b)
}
func (m *ListEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventRequest.Marshal(b, m, deterministic)
}
func (m *ListEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventRequest.Merge(m, src)
}
func (m *ListEventRequest) XXX_Size() int {
	return xxx_messageInfo_ListEventRequest.Size(m)
}
func (m *ListEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventRequest proto.InternalMessageInfo

func (m *ListEventRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListEventRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListEventRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListEventRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListEventsResponse struct {
	Results              []*Event        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page                 *query.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListEventsResponse) Reset()         { *m = ListEventsResponse{} }
func (m *ListEventsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEventsResponse) ProtoMessage()    {}
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_123714ce407bb634, []int{22}
}

func (m *ListEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsResponse.Unmarshal(m, b)
}
func (m *ListEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsResponse.Marshal(b, m, deterministic)
}
func (m *ListEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsResponse.Merge(m, src)
}
func (m *ListEventsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEventsResponse.Size(m)
}
func (m *ListEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsResponse proto.InternalMessageInfo

func (m *ListEventsResponse) GetResults() []*Event {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListEventsResponse) GetPage() *query.PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "api.test.VersionResponse")
	proto.RegisterType((*Application)(nil), "api.test.Application")
	proto.RegisterType((*CreateApplicationRequest)(nil), "api.test.CreateApplicationRequest")
	proto.RegisterType((*CreateApplicationResponse)(nil), "api.test.CreateApplicationResponse")
	proto.RegisterType((*ReadApplicationRequest)(nil), "api.test.ReadApplicationRequest")
	proto.RegisterType((*ReadApplicationResponse)(nil), "api.test.ReadApplicationResponse")
	proto.RegisterType((*UpdateApplicationRequest)(nil), "api.test.UpdateApplicationRequest")
	proto.RegisterType((*UpdateApplicationResponse)(nil), "api.test.UpdateApplicationResponse")
	proto.RegisterType((*DeleteApplicationRequest)(nil), "api.test.DeleteApplicationRequest")
	proto.RegisterType((*DeleteApplicationResponse)(nil), "api.test.DeleteApplicationResponse")
	proto.RegisterType((*ListApplicationRequest)(nil), "api.test.ListApplicationRequest")
	proto.RegisterType((*ListApplicationsResponse)(nil), "api.test.ListApplicationsResponse")
	proto.RegisterType((*Event)(nil), "api.test.Event")
	proto.RegisterType((*CreateEventRequest)(nil), "api.test.CreateEventRequest")
	proto.RegisterType((*CreateEventResponse)(nil), "api.test.CreateEventResponse")
	proto.RegisterType((*ReadEventRequest)(nil), "api.test.ReadEventRequest")
	proto.RegisterType((*ReadEventResponse)(nil), "api.test.ReadEventResponse")
	proto.RegisterType((*UpdateEventRequest)(nil), "api.test.UpdateEventRequest")
	proto.RegisterType((*UpdateEventResponse)(nil), "api.test.UpdateEventResponse")
	proto.RegisterType((*DeleteEventRequest)(nil), "api.test.DeleteEventRequest")
	proto.RegisterType((*DeleteEventResponse)(nil), "api.test.DeleteEventResponse")
	proto.RegisterType((*ListEventRequest)(nil), "api.test.ListEventRequest")
	proto.RegisterType((*ListEventsResponse)(nil), "api.test.ListEventsResponse")
}

func init() {
	proto.RegisterFile("github.com/seizadi/test/pkg/pb/service.proto", fileDescriptor_123714ce407bb634)
}

var fileDescriptor_123714ce407bb634 = []byte{
	// 1305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0x41, 0x6f, 0xdc, 0x44,
	0x14, 0xae, 0x37, 0xdb, 0x4d, 0xfa, 0xd2, 0x34, 0xe9, 0x44, 0x69, 0xbd, 0x6e, 0x68, 0xb7, 0xae,
	0x28, 0x6d, 0xda, 0xd8, 0xed, 0x82, 0x54, 0x91, 0x56, 0x85, 0xb4, 0x04, 0xd1, 0x16, 0x50, 0xd9,
	0x04, 0x84, 0x7a, 0x59, 0xcd, 0xae, 0x67, 0x9d, 0x21, 0x5e, 0xcf, 0xd4, 0x33, 0x9b, 0x92, 0x22,
	0x84, 0xc4, 0x81, 0x03, 0x47, 0xf8, 0x19, 0xfc, 0x00, 0x48, 0x2e, 0x1c, 0x38, 0x72, 0xe4, 0x86,
	0x04, 0x17, 0xf8, 0x13, 0xdc, 0x90, 0xc7, 0xb3, 0xbb, 0xb6, 0xd7, 0x9b, 0x26, 0x11, 0x70, 0xe0,
	0x66, 0x7b, 0xbe, 0xf9, 0xde, 0x7b, 0xdf, 0x7c, 0xf3, 0x66, 0x64, 0xb8, 0xee, 0x53, 0xb9, 0xd9,
	0x6b, 0x39, 0x6d, 0xd6, 0x75, 0x05, 0xa1, 0xcf, 0xb1, 0x47, 0x5d, 0x49, 0x84, 0x74, 0xf9, 0x96,
	0xef, 0xf2, 0x96, 0x2b, 0x48, 0xb4, 0x4d, 0xdb, 0xc4, 0xe1, 0x11, 0x93, 0x0c, 0x4d, 0x61, 0x4e,
	0x9d, 0x78, 0xd8, 0xaa, 0xf9, 0x8c, 0xf9, 0x01, 0x71, 0xd5, 0xf7, 0x56, 0xaf, 0xe3, 0x76, 0x28,
	0x09, 0xbc, 0x66, 0x17, 0x8b, 0xad, 0x04, 0x6b, 0x5d, 0xc8, 0x23, 0x24, 0xed, 0x12, 0x21, 0x71,
	0x97, 0x6b, 0xc0, 0xa2, 0x06, 0x60, 0x4e, 0x5d, 0x1c, 0x86, 0x4c, 0x62, 0x49, 0x59, 0x28, 0xf4,
	0xe8, 0xed, 0x54, 0x62, 0xc1, 0x4e, 0x47, 0x26, 0x3c, 0xed, 0x65, 0x9f, 0x84, 0xcb, 0xdb, 0x38,
	0xa0, 0x1e, 0x96, 0xc4, 0x1d, 0x79, 0xd0, 0x93, 0xaf, 0xa7, 0xc0, 0xe2, 0x19, 0xf6, 0x7d, 0x12,
	0xb9, 0x8c, 0x2b, 0xfa, 0x82, 0x50, 0x2b, 0xa9, 0x50, 0x34, 0xec, 0xb0, 0x56, 0xc0, 0x3e, 0x65,
	0x9c, 0x84, 0xe9, 0x90, 0x3e, 0x8b, 0xba, 0x03, 0x8a, 0xf8, 0x45, 0xcf, 0x7d, 0x38, 0x6e, 0x2e,
	0x96, 0x01, 0x16, 0xcb, 0x98, 0xf3, 0x65, 0xc9, 0x58, 0xb0, 0x45, 0xa5, 0xfb, 0xb4, 0x47, 0xa2,
	0x1d, 0xb7, 0xcd, 0x82, 0x80, 0xb4, 0x63, 0x9e, 0x26, 0xe3, 0x24, 0xc2, 0x92, 0x45, 0xfd, 0x3c,
	0xd6, 0x0e, 0xce, 0x15, 0xf1, 0xb6, 0x1b, 0x11, 0xc1, 0x7a, 0x51, 0x9b, 0x0c, 0x1e, 0x34, 0xcd,
	0xc6, 0x01, 0xca, 0x49, 0x18, 0x55, 0x46, 0x43, 0x35, 0xfb, 0xe5, 0xa9, 0xcf, 0xcd, 0x9c, 0xa4,
	0xef, 0x1f, 0x98, 0x75, 0x84, 0x4f, 0x7d, 0xce, 0xf1, 0xd9, 0xd7, 0x60, 0xf6, 0x23, 0x12, 0x09,
	0xca, 0xc2, 0x06, 0x11, 0x9c, 0x85, 0x82, 0x20, 0x13, 0x26, 0xb7, 0x93, 0x4f, 0xa6, 0x51, 0x33,
	0xae, 0x9c, 0x68, 0xf4, 0x5f, 0xed, 0xaf, 0x0c, 0x98, 0x5e, 0xe5, 0x3c, 0xa0, 0x6d, 0xb5, 0x70,
	0xe8, 0x16, 0x94, 0xa8, 0xa7, 0x40, 0xd3, 0xf5, 0x05, 0x47, 0xf1, 0x3b, 0x11, 0x6f, 0x3b, 0x0f,
	0x3c, 0x12, 0x4a, 0xda, 0xa1, 0x24, 0xba, 0x37, 0xb7, 0xb7, 0x5b, 0x3d, 0x09, 0x80, 0x2a, 0x82,
	0x44, 0x14, 0x07, 0x57, 0x8c, 0x46, 0x89, 0x7a, 0x08, 0x41, 0x39, 0xc4, 0x5d, 0x62, 0x96, 0x14,
	0xbf, 0x7a, 0x46, 0x35, 0x98, 0xf6, 0x88, 0x68, 0x47, 0x54, 0xa5, 0x6b, 0x4e, 0xa8, 0xa1, 0xf4,
	0xa7, 0x95, 0xa9, 0xbd, 0xdd, 0x6a, 0x79, 0xca, 0xa8, 0x19, 0xf6, 0x23, 0x30, 0xef, 0x47, 0x04,
	0x4b, 0x92, 0xca, 0xa6, 0x41, 0x9e, 0xf6, 0x88, 0x90, 0xc8, 0x85, 0x49, 0x8e, 0x77, 0x02, 0x86,
	0x53, 0x99, 0xe9, 0xed, 0xe2, 0xa4, 0xe1, 0x7d, 0x94, 0xfd, 0x10, 0xaa, 0x05, 0x64, 0x5a, 0x8c,
	0x65, 0xa8, 0x44, 0x44, 0xf4, 0x02, 0xb9, 0x3f, 0x99, 0x06, 0xd9, 0x3d, 0x38, 0xd3, 0x20, 0xd8,
	0x2b, 0x48, 0xeb, 0xe5, 0x17, 0x6a, 0xa5, 0x94, 0x79, 0x0d, 0x2a, 0x6a, 0x0b, 0x0b, 0xa5, 0xcd,
	0x74, 0x7d, 0xd1, 0xe9, 0xaf, 0xb2, 0x0a, 0xfc, 0x76, 0x3c, 0xb6, 0x4e, 0xb4, 0x75, 0x1b, 0x1a,
	0x6b, 0xbf, 0x03, 0x67, 0x47, 0xc2, 0x1e, 0xad, 0x80, 0x2f, 0xc0, 0xfc, 0x90, 0x7b, 0xff, 0x8c,
	0xb2, 0xa8, 0x9e, 0x2b, 0xc6, 0x72, 0x92, 0x5e, 0xe3, 0xf4, 0x9b, 0x51, 0x52, 0xcf, 0x7b, 0x58,
	0x6c, 0x0d, 0x4a, 0x79, 0x08, 0xd5, 0x82, 0x04, 0x8e, 0x56, 0xcc, 0x2a, 0x98, 0x6f, 0x91, 0x80,
	0x14, 0x16, 0x73, 0xb0, 0xf5, 0xb0, 0xcf, 0x41, 0xb5, 0x80, 0x22, 0x49, 0xc7, 0xfe, 0xc3, 0x80,
	0x33, 0xef, 0x52, 0x21, 0x0b, 0xb5, 0xaa, 0x74, 0x68, 0x20, 0x49, 0xa4, 0x43, 0x9c, 0xcd, 0xaf,
	0x63, 0x3c, 0x46, 0x43, 0xbf, 0xa1, 0x61, 0xe8, 0x06, 0x4c, 0xb1, 0xc8, 0x23, 0x51, 0xb3, 0xb5,
	0xa3, 0xd5, 0x5a, 0xc8, 0x4e, 0x59, 0x67, 0x91, 0x8c, 0x27, 0x4c, 0x2a, 0xd8, 0xbd, 0x9d, 0x94,
	0x55, 0x26, 0x0e, 0x6e, 0x15, 0x74, 0x03, 0x2a, 0x1c, 0xfb, 0x34, 0xf4, 0xcd, 0xb2, 0x9a, 0x65,
	0x66, 0x67, 0x3d, 0x8e, 0xc7, 0xb4, 0x8a, 0x09, 0xce, 0x7e, 0x06, 0x66, 0xae, 0x48, 0x31, 0x58,
	0x10, 0x17, 0x26, 0x13, 0xad, 0x85, 0x69, 0xd4, 0x26, 0xf6, 0xb1, 0x84, 0x46, 0xa1, 0x25, 0x28,
	0x73, 0xec, 0x13, 0x5d, 0xe2, 0x99, 0x91, 0xe0, 0xe4, 0x41, 0xd8, 0x61, 0x0d, 0x85, 0xb1, 0xff,
	0x32, 0xe0, 0xf8, 0xda, 0x36, 0x09, 0xe5, 0x7f, 0xdc, 0x68, 0xd0, 0xeb, 0x00, 0x24, 0x8e, 0xdb,
	0x8c, 0xcf, 0x4a, 0xad, 0xd3, 0xa8, 0x77, 0x37, 0xfa, 0x07, 0x69, 0xe3, 0x84, 0x42, 0xc7, 0xef,
	0xe8, 0x0e, 0x9c, 0xc2, 0xc3, 0xba, 0x9b, 0xd4, 0x33, 0x8f, 0xef, 0x67, 0xb1, 0x99, 0x14, 0xf8,
	0x81, 0x97, 0xea, 0x70, 0x6f, 0x00, 0x4a, 0x9a, 0x92, 0x12, 0xa0, 0xef, 0xaa, 0xab, 0xf9, 0x1d,
	0x38, 0x3b, 0x94, 0x3b, 0x01, 0x0e, 0xba, 0xda, 0x5d, 0x98, 0xcf, 0x10, 0xe8, 0x05, 0x7b, 0x25,
	0xb7, 0x83, 0x46, 0x08, 0xfa, 0x7b, 0x87, 0xc1, 0x5c, 0xdc, 0x52, 0x32, 0xe1, 0xff, 0xd5, 0x1e,
	0x76, 0x07, 0x4e, 0xa7, 0x02, 0x1e, 0x36, 0x5d, 0x01, 0x28, 0x69, 0x1b, 0x47, 0xd4, 0xeb, 0x48,
	0xbd, 0xea, 0x2e, 0xcc, 0x67, 0x82, 0x1e, 0x36, 0xe9, 0xdb, 0x80, 0x92, 0xe6, 0x72, 0x04, 0x95,
	0xed, 0x05, 0x98, 0xcf, 0x4c, 0xd6, 0x3d, 0xe9, 0x37, 0x03, 0xe6, 0xe2, 0xed, 0x9a, 0xa1, 0xfc,
	0x1f, 0x75, 0xa3, 0x2d, 0x40, 0x83, 0xf2, 0x86, 0x7d, 0xe8, 0x6a, 0xbe, 0x0f, 0x8d, 0x2e, 0xf4,
	0x11, 0x3a, 0x50, 0xfd, 0x87, 0xe3, 0x70, 0x32, 0xdd, 0xf7, 0xd0, 0x53, 0xa8, 0x24, 0xbb, 0x0a,
	0xd9, 0xc3, 0x00, 0xe3, 0xae, 0x22, 0xd6, 0xa5, 0x7d, 0x31, 0x7a, 0xc1, 0xce, 0x7f, 0xf9, 0xcb,
	0x9f, 0xdf, 0x96, 0x4c, 0x7b, 0xc6, 0x4d, 0xf5, 0x02, 0xb1, 0x32, 0x30, 0xa6, 0x80, 0x72, 0xbc,
	0x2f, 0x50, 0x6d, 0x48, 0x56, 0x7c, 0xc5, 0xb0, 0x2e, 0xee, 0x83, 0xd0, 0xc1, 0x2e, 0xab, 0x60,
	0x35, 0x74, 0x3e, 0x13, 0xcc, 0xfd, 0x8c, 0x7a, 0x4e, 0xff, 0xfa, 0xda, 0xa4, 0xde, 0xe7, 0xe8,
	0x27, 0x03, 0x2a, 0x89, 0xb5, 0xd3, 0x85, 0x8e, 0xbb, 0x19, 0xa4, 0x0b, 0x1d, 0x7b, 0x78, 0xdb,
	0xfc, 0xd7, 0x1f, 0xab, 0xa5, 0xa9, 0x63, 0x2a, 0x03, 0xcf, 0xba, 0x9c, 0xcb, 0x40, 0x97, 0xeb,
	0xe4, 0x32, 0x19, 0xe8, 0xf0, 0xe4, 0x66, 0xfd, 0xb0, 0x53, 0xd0, 0xd7, 0x06, 0x54, 0x92, 0x3d,
	0x92, 0xae, 0x62, 0xdc, 0x95, 0x20, 0x5d, 0xc5, 0xf8, 0x33, 0xff, 0xd6, 0xde, 0x6e, 0x75, 0x26,
	0x73, 0x0d, 0x4e, 0x24, 0x5d, 0x7a, 0x91, 0xa4, 0x6d, 0x28, 0xc7, 0xc6, 0x4d, 0xaf, 0x63, 0xf1,
	0xdd, 0xc1, 0xb2, 0xc7, 0x22, 0x06, 0x86, 0xb7, 0x17, 0x54, 0xd4, 0x59, 0x94, 0x75, 0x8d, 0xa5,
	0x0f, 0x90, 0x39, 0xa3, 0xfe, 0x73, 0x19, 0x2a, 0xc9, 0x26, 0x41, 0xcd, 0x81, 0x69, 0x17, 0xf3,
	0x86, 0x4c, 0x77, 0x09, 0xeb, 0xa5, 0x31, 0xa3, 0x3a, 0xa4, 0xa9, 0x42, 0x22, 0x7b, 0xd2, 0x55,
	0xc7, 0x5d, 0xca, 0xa2, 0x58, 0x5b, 0xd4, 0xca, 0x1a, 0x30, 0x43, 0x7e, 0xae, 0x70, 0x4c, 0x53,
	0xd7, 0x14, 0xb5, 0x85, 0x4c, 0x4d, 0x3d, 0xaa, 0xde, 0x77, 0x43, 0x43, 0x2e, 0xe6, 0xcd, 0x36,
	0xae, 0x88, 0x82, 0xde, 0x6c, 0x7b, 0x29, 0x13, 0x7e, 0x6c, 0xd5, 0x06, 0xf1, 0x5e, 0x68, 0xbf,
	0x6b, 0xf5, 0x83, 0x83, 0x51, 0x34, 0xf0, 0xdd, 0x62, 0xde, 0x53, 0xe3, 0x92, 0x2d, 0xea, 0xe5,
	0xd7, 0xf6, 0x76, 0xab, 0x93, 0xfa, 0x0e, 0x94, 0x28, 0xb4, 0x34, 0x5e, 0xa1, 0x0f, 0xb4, 0xbf,
	0xac, 0xac, 0x7b, 0x32, 0xf1, 0x16, 0x0b, 0xc6, 0x86, 0x9e, 0x9a, 0x55, 0x31, 0x4e, 0xa0, 0xfe,
	0x02, 0x0f, 0xdd, 0x74, 0xef, 0x77, 0xe3, 0x9b, 0xd5, 0xef, 0x0d, 0xf4, 0x18, 0xca, 0x1b, 0x6b,
	0xeb, 0x1b, 0xf6, 0x7d, 0x98, 0x59, 0x67, 0x9b, 0x84, 0x06, 0xb5, 0x35, 0xf5, 0xaf, 0x02, 0x5d,
	0xd8, 0x94, 0x92, 0x8b, 0x15, 0xd7, 0x1d, 0xf3, 0x1f, 0xc3, 0x3a, 0xad, 0xdf, 0xde, 0xf4, 0xbb,
	0x98, 0x06, 0xf1, 0x78, 0x7d, 0xe2, 0xa6, 0x73, 0xc3, 0x2e, 0xbb, 0xdb, 0x37, 0xdd, 0xa5, 0x92,
	0x51, 0xaa, 0xcf, 0xa5, 0x8c, 0xec, 0x7e, 0x22, 0x58, 0xb8, 0x32, 0xf2, 0xe5, 0xc9, 0x25, 0xb8,
	0x08, 0xb0, 0xca, 0xe9, 0x23, 0xb2, 0xb3, 0xda, 0x93, 0x9b, 0x68, 0x7e, 0xaa, 0x64, 0xcd, 0xc4,
	0x4f, 0x2c, 0xa2, 0xcf, 0x15, 0xae, 0x56, 0x6a, 0xcd, 0xc1, 0xa9, 0x0c, 0xe8, 0xd8, 0x93, 0x8b,
	0xfb, 0xff, 0x5d, 0xb9, 0xcd, 0x5b, 0xad, 0x8a, 0x3a, 0xe6, 0x5f, 0xfd, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x9c, 0x86, 0x53, 0xbe, 0x89, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApplicationsClient is the client API for Applications service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApplicationsClient interface {
	// Use this method to create a Application information.
	Create(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*CreateApplicationResponse, error)
	// Use this method to read a Application information by identifier.
	Read(ctx context.Context, in *ReadApplicationRequest, opts ...grpc.CallOption) (*ReadApplicationResponse, error)
	// Use this method to update a Application information.
	Update(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*UpdateApplicationResponse, error)
	// Use this method to delete a particular Application.
	Delete(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error)
	// Use this method to retrieve all the Applications.
	List(ctx context.Context, in *ListApplicationRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error)
}

type applicationsClient struct {
	cc *grpc.ClientConn
}

func NewApplicationsClient(cc *grpc.ClientConn) ApplicationsClient {
	return &applicationsClient{cc}
}

func (c *applicationsClient) Create(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*CreateApplicationResponse, error) {
	out := new(CreateApplicationResponse)
	err := c.cc.Invoke(ctx, "/api.test.Applications/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) Read(ctx context.Context, in *ReadApplicationRequest, opts ...grpc.CallOption) (*ReadApplicationResponse, error) {
	out := new(ReadApplicationResponse)
	err := c.cc.Invoke(ctx, "/api.test.Applications/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) Update(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*UpdateApplicationResponse, error) {
	out := new(UpdateApplicationResponse)
	err := c.cc.Invoke(ctx, "/api.test.Applications/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) Delete(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error) {
	out := new(DeleteApplicationResponse)
	err := c.cc.Invoke(ctx, "/api.test.Applications/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) List(ctx context.Context, in *ListApplicationRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error) {
	out := new(ListApplicationsResponse)
	err := c.cc.Invoke(ctx, "/api.test.Applications/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationsServer is the server API for Applications service.
type ApplicationsServer interface {
	// Use this method to create a Application information.
	Create(context.Context, *CreateApplicationRequest) (*CreateApplicationResponse, error)
	// Use this method to read a Application information by identifier.
	Read(context.Context, *ReadApplicationRequest) (*ReadApplicationResponse, error)
	// Use this method to update a Application information.
	Update(context.Context, *UpdateApplicationRequest) (*UpdateApplicationResponse, error)
	// Use this method to delete a particular Application.
	Delete(context.Context, *DeleteApplicationRequest) (*DeleteApplicationResponse, error)
	// Use this method to retrieve all the Applications.
	List(context.Context, *ListApplicationRequest) (*ListApplicationsResponse, error)
}

func RegisterApplicationsServer(s *grpc.Server, srv ApplicationsServer) {
	s.RegisterService(&_Applications_serviceDesc, srv)
}

func _Applications_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.test.Applications/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).Create(ctx, req.(*CreateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.test.Applications/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).Read(ctx, req.(*ReadApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.test.Applications/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).Update(ctx, req.(*UpdateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.test.Applications/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).Delete(ctx, req.(*DeleteApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.test.Applications/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).List(ctx, req.(*ListApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Applications_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.test.Applications",
	HandlerType: (*ApplicationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Applications_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Applications_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Applications_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Applications_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Applications_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/seizadi/test/pkg/pb/service.proto",
}

// EventsClient is the client API for Events service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventsClient interface {
	// Use this method to create a Event information.
	Create(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	// Use this method to read a Event information by identifier.
	Read(ctx context.Context, in *ReadEventRequest, opts ...grpc.CallOption) (*ReadEventResponse, error)
	// Use this method to update a Event information.
	Update(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateEventResponse, error)
	// Use this method to delete a particular Event.
	Delete(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error)
	// Use this method to retrieve all the Events.
	List(ctx context.Context, in *ListEventRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
}

type eventsClient struct {
	cc *grpc.ClientConn
}

func NewEventsClient(cc *grpc.ClientConn) EventsClient {
	return &eventsClient{cc}
}

func (c *eventsClient) Create(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, "/api.test.Events/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsClient) Read(ctx context.Context, in *ReadEventRequest, opts ...grpc.CallOption) (*ReadEventResponse, error) {
	out := new(ReadEventResponse)
	err := c.cc.Invoke(ctx, "/api.test.Events/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsClient) Update(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateEventResponse, error) {
	out := new(UpdateEventResponse)
	err := c.cc.Invoke(ctx, "/api.test.Events/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsClient) Delete(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error) {
	out := new(DeleteEventResponse)
	err := c.cc.Invoke(ctx, "/api.test.Events/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsClient) List(ctx context.Context, in *ListEventRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, "/api.test.Events/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsServer is the server API for Events service.
type EventsServer interface {
	// Use this method to create a Event information.
	Create(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	// Use this method to read a Event information by identifier.
	Read(context.Context, *ReadEventRequest) (*ReadEventResponse, error)
	// Use this method to update a Event information.
	Update(context.Context, *UpdateEventRequest) (*UpdateEventResponse, error)
	// Use this method to delete a particular Event.
	Delete(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error)
	// Use this method to retrieve all the Events.
	List(context.Context, *ListEventRequest) (*ListEventsResponse, error)
}

func RegisterEventsServer(s *grpc.Server, srv EventsServer) {
	s.RegisterService(&_Events_serviceDesc, srv)
}

func _Events_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.test.Events/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).Create(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Events_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.test.Events/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).Read(ctx, req.(*ReadEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Events_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.test.Events/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).Update(ctx, req.(*UpdateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Events_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.test.Events/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).Delete(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Events_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.test.Events/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).List(ctx, req.(*ListEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Events_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.test.Events",
	HandlerType: (*EventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Events_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Events_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Events_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Events_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Events_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/seizadi/test/pkg/pb/service.proto",
}
